services:
  quadruped_navigation:
    build:
      context: .
      dockerfile: Dockerfile

    platform: linux/arm64
    image: quadruped_jazzy
    container_name: quadruped_navigation
    hostname: quadruped_navigation

    # restart: unless-stopped
    stdin_open: true
    tty: true

    environment:
      - ROS_DISTRO=jazzy
      - DISPLAY=host.docker.internal:0

    volumes:
      - .:/home/ubuntu/quadruped-navigation:rw