services:
  quadruped_navigation:
    build:
      context: .
      dockerfile: Dockerfile

    platform: linux/amd64
    image: quadruped_jazzy
    container_name: quadruped_navigation
    hostname: quadruped_navigation

    # restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true

    environment:
      - ROS_DISTRO=jazzy
      - DISPLAY=${DISPLAY:-:0}

    volumes:
      - .:/root/ros2_ws/quadruped-navigation:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-~/.Xauthority}:/home/ubuntu/.Xauthority:ro
      - /dev/dri:/dev/dri